# Generated by Django 4.2.2 on 2023-06-17 00:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('detector', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Disease',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('disease_name', models.CharField(blank=True, max_length=100)),
                ('symptoms', models.TextField(blank=True)),
                ('treatment', models.TextField(blank=True)),
            ],
        ),
    ]
